version: '3.2'
services:
  frontend:
    image: av-app-image
    ports:
      - 4200:80

  cypress:
    image: "cypress/included:4.6.0"
    depends_on:
      - frontend
    network_mode: "host"

    working_dir: /app/apps/frontend-e2e

    environment:
      - CYPRESS_baseUrl=http://localhost:4200

    volumes:
      - ./:/app
